config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'users/show'
    get 'users/edit'
  end
  devise_for :users,skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admins,skip: [:registrations, :passwords], controllers:{
    sessions: "admin/sessions"
  }
  scope module: :public do
    resources :users, only:[:show, :edit, :update] do
      member do
        get :favorites
      end
    end
    resources :messages do
      resource :favorites, only:[:create, :destroy]
    end

    root to: 'homes#top'
  end

  namespace :admin do
    resources :users, only:[:index, :show, :update]
    resources :messages
    resources :tags

    root to: 'homes#top'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :message
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :tag, optional: true
  has_many :favorites, dependent: :destroy

  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :favorites, dependent: :destroy
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController

  def index
    @messages = Message.all
  end
  def edit
    @message = Message.find(params[:id])
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to request.referer
  end
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController

  def index
    @tags = Tag.all
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path
    else
      @tags = Tag.all
      render 'index'
    end
  end
  
  def edit
    @tag = Tag.find(params[:id])
  end
  
  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path
    else
      render "edit"
    end
  end


  private

  def tag_params
    params.require(:tag).permit(:tagname)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/top.html.erb
<h1>管理者トップページ</h1>

app/views/admin/messages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <h4>ことば一覧</h4>
      <% @messages.each do |message| %>
      <div class="message-index smart text-center">
        <%= safe_join(message.text.split("\n"),tag(:br)) %><br>
        <div class="text-center">
          <%= link_to "編集", edit_admin_message_path(message.id), class: "btn btn-success btn-sm" %>
          <%= link_to "削除", admin_message_path(message.id), method: :delete, class: "btn btn-danger btn-sm" %>
        </div>
      </div><br>
      <% end %>

      <table class="table pc">
        <% @messages.each do |message| %>
        <tr>
          <td><%= message.user.name %></td>
          <td class="col-8"><%= safe_join(message.text.split("\n"),tag(:br)) %></td>
          <td><%= link_to "編集", edit_admin_message_path(message.id), class: "btn btn-success btn-sm" %></td>
          <td><%= link_to "削除", admin_message_path(message.id), method: :delete, class: "btn btn-danger btn-sm" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/admin/tags/edit.html.erb
<div class="container">
  <div class="row">
    <div>
      <%= form_with model: @tag, url: admin_tags_path(@tag.id), method: :patch do |f| %>
      <div class="field">
        <%= f.label :タグ %>
        <%= f.text_field :tagname, placeholder: "タグ名" %>
        <%= f.submit, "更新", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container">
  <div class="row">
    <div>
      <%= form_with model: @tag, url: admin_tags_path do |f| %>
      <div class="field">
        <%= f.label :タグ %>
        <%= f.text_field :tagname, placeholder: "タグ名" %>
        <%= f.submit "新規登録", class:"btn btn-success" %>
      </div>
      <% end %>
    </div>
    <% if @tags.count != 0 %>
    <table class="table">
      <thead>
        <tr>
          <th>タグ名</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @tags.each do |tag| %>
        <tr>
          <td><%= tag.tagname %></td>
          <td><%= link_to "編集", edit_admin_tag_path(tag.id), class:"btn btn-primary" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
      <div class="text-center">
        <p>@heartful words</p>
        <p>こころをあたたかく</p>
      </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <!--ユーザログイン-->
      <% if admin_signed_in? %>
      <a class="navbar-brand" href="/admin">
        <p>ことばのひろば</p>
      </a>
      <% else %>
      <a class="navbar-brand" href="/">
        <p>ことばのひろば</p>
      </a>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "すきなことば", favorites_user_path(current_user),class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
            <%= link_to "マイページ", user_path(current_user),class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'nav-link text-dark' %>
          </li>
    　<% elsif admin_signed_in?%>
          <li class="nav-item">
            <%= link_to "ことばリスト", admin_messages_path %>
          </li>
          <li class="nav-item">
            <%= link_to "タグ", admin_tags_path %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
          </li>
      <% else %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path,class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path,class: 'nav-link text-dark' %>
          </li>
      <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeartfulWords</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>